version: "3.8"

services: # ==> daftar services yg di gunakan
  golang:      # ==> container golang
    build: .
    ports:
      - 7773:8888
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - APP_SECRET=123ABC@12
      - DB_NAME=postgres
      - DB_HOST=aws-0-ap-southeast-1.pooler.supabase.com
      - DB_PORT=5432
      - DB_USER=postgres.viowfpzjtxzzugeftjpm
      - DB_PASSWORD=AIeax8knSVmXirIq
    # networks:
    #   - coffee-shop-networking
    # depends_on:
    #   - db
    restart: always


#   db:       # ==> container db
#     container_name: db-coffee-shop
#     image: postgres
#     ports:          # ==> ports forward hanya saat development
#       - 5333:5432
#     environment:
#       - POSTGRES_PASSWORD=1
#     volumes:
#       - dataCoffeeShop:/var/lib/postgresql/data
#     networks:
#       - coffee-shopNET
#     restart: always
    

# volumes:
#     dataCoffeeShop:
#       external:
#         true


# name: coffee_shop_be


# networks:
#   coffee-shopNET:

