version: "3.8"

services:   # daftar container yg di buat
  golang:      # container web
    build: .        # lokasi dockerfile
    ports:
      - 8814:8888
    volumes:
      - .:/app
    depends_on:
      - db
    restart: always

  db:       # container db
    container_name: be-go-coffee-go
    image: postgres
    ports:          #  ports di forward hanya selama develop
      - 5444:5432
    volumes:
      - ./db-data:/var/lib/postgresql/16/main
    environment:
      - POSTGRES_DB=go-coffee-go
      - POSTGRES_PASSWORD=1
      - POSTGRES_USER=postgres
    restart: always
    

