version: "3.8"

services:   # daftar container yg akan di buat
  golang:      # container web
    build: .        # lokasi dockerfile
    ports:
      - 8814:8888
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - APP_SECRET=123ABC@12
    depends_on:
      - db
    restart: always

  db:       # container db
    container_name: be-go-coffee-go
    image: postgres
    ports:          #  ports di forward hanya selama develop
      - 5444:5432
    volumes:
      - ./db-data:/var/lib/postgresql/16/main
    environment:
      - POSTGRES_DB=go-coffee-go
      - POSTGRES_PASSWORD=1
      - POSTGRES_USER=postgres
    restart: always
    


  # masih mencoba
    
# volumes:
#     dataCoffeeShop:
#       external:
#         true


# name: coffee-shop-go


# networks:
#   coffee-shop-go:

